export const VI_STRINGS = {
  footer: '© High School Hub. All rights reserved.',
  prompt: 'Vui lòng chọn vai trò',
  student: 'HỌC SINH',
  teacher: 'GIÁO VIÊN',
  or: 'hay',
  skip: 'Bỏ qua',
  continue: 'Tiếp tục',
  back: 'Quay lại',
  welcome: 'Chào mừng',
  loginTitle: 'Đăng nhập',
  loginDescriptionPrefix: 'Chào mừng bạn đến với',
  loginDescriptionStudent: 'vui lòng nhập thông tin để đăng nhập bên dưới',
  loginDescriptionTeacher:
    'vui lòng xác thực tài khoản giảng dạy của bạn bên dưới',
  phone: 'Số điện thoại',
  phonePlaceholder: 'Nhập số điện thoại',
  next: 'Tiếp theo',
  password: 'Mật khẩu',
  passwordPlaceholder: 'Nhập mật khẩu của bạn',
  forgotPassword: 'Quên mật khẩu',
  altLogin: 'HOẶC ĐĂNG NHẬP BẰNG',
  fingerprint: 'Vân tay',
  faceId: 'Face ID',
  loginSuccess: 'Đăng nhập\nthành công',
  searchTitle: 'Tìm kiếm',
  searchRecent: 'Gần đây',
  searchClearAll: 'Xóa tất cả',
  searchFeatured: 'Chức năng nổi bật',
  searchAll: 'Tất cả',
  searchQuickSuggestions: 'Gợi ý nhanh',
  notificationsTitle: 'Thông báo',
  notificationsMarkAllRead: 'Đánh dấu đã đọc',
  notificationsTabAll: 'Tất cả',
  notificationsTabUnread: 'Chưa đọc',
} as const;
