export type ScreenKey =
  | 'splash'
  | 'role-selection'
  | 'student-onboarding'
  | 'teacher-onboarding'
  | 'login'
  | 'student-dashboard'
  | 'student-attendance'
  | 'student-schedule'
  | 'student-search'
  | 'student-create-post'
  | 'student-notifications'
  | 'student-settings'
  | 'student-tuition-payment'
  | 'student-profile'
  | 'student-edit-profile'
  | 'student-exam-schedule'
  | 'student-homework'
  | 'student-chat'
  | 'student-chat-new'
  | 'student-classroom'
  | 'student-all-features'
  | 'student-quiz-question'
  | 'student-quiz-result'
  | 'student-quiz-answer-review'
  | 'student-quiz-ai-analysis'
  | 'student-scorebook'
  | 'student-forum'
  | 'student-leave-request'
  | 'student-leave-request-preview'
  | 'teacher-dashboard'
  | 'teacher-search'
  | 'teacher-notifications'
  | 'teacher-settings';

export type RoleKey = 'student' | 'teacher';
